### ISSUE TITLE
Ruby 3 Support

### ISSUE THREAD

**Issue by Otterpocket** [what3words/w3w-ruby-wrapper#6]
![image](https://user-images.githubusercontent.com/7274458/229103498-1bbbf6a8-3c8d-45ae-9b9a-1ffc2b25292e.png)

**Comment by ja** [comment]
I tried to add what3words to my Gemfile and get the following:

> Could not find compatible versions
> Because what3words >= 3.0.0 depends on Ruby ~> 2.6  and Gemfile depends on what3words ~> 3.3,  Ruby ~> 2.6 is required.
> So, because current Ruby version is = 3.3.6,  version solving has failed.
> 

Checking the gemspec it seems that ruby 2.6 is still required rather than it being specified as the minimum ruby version so I don't understand how this issue was resolved?
